<?php

return [
    [
        'name' => 'state',
        'title' => '是否启用加密',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'selector',
        'title' => '密码文本框选择器',
        'type' => 'string',
        'group' => '',
        'visible' => '',
        'content' => [],
        'value' => 'input[type=password]',
        'rule' => 'required',
        'msg' => '',
        'tip' => '多个选择器使用半角,进行分隔',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'excludedurls',
        'title' => '排除页面列表',
        'type' => 'text',
        'group' => '',
        'visible' => '',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '多个页面换行分隔',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'key',
        'title' => '加解密KEY',
        'type' => 'string',
        'content' => [],
        'value' => '98CWtos7cHTByRg0',
        'rule' => 'required;length(16)',
        'msg' => '',
        'tip' => '用于加解密字符串，长度必须为16位',
        'ok' => '',
        'extend' => '',
    ],
];
