<?php

return [
    [
        'name' => 'text',
        'title' => '默认文本',
        'type' => 'string',
        'content' => [],
        'value' => 'Hello world!',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'size',
        'title' => '默认宽高',
        'type' => 'number',
        'content' => [],
        'value' => '300',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'padding',
        'title' => '默认边距',
        'type' => 'number',
        'content' => [],
        'value' => '15',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'format',
        'title' => '默认格式',
        'type' => 'radio',
        'content' => [
            'png' => 'PNG',
            'svg' => 'SVG(不支持标签)',
        ],
        'value' => 'png',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'errorlevel',
        'title' => '容错级别',
        'type' => 'radio',
        'content' => [
            'low' => '低',
            'medium' => '中',
            'quartile' => '高',
            'high' => '超高',
        ],
        'value' => 'medium',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'foreground',
        'title' => '前景色',
        'type' => 'string',
        'content' => [],
        'value' => '#000000',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'background',
        'title' => '背景色',
        'type' => 'string',
        'content' => [],
        'value' => '#ffffff',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'label',
        'title' => '默认标签',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'labelfontsize',
        'title' => '标签字体大小',
        'type' => 'number',
        'content' => [],
        'value' => '14',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'labelfontpath',
        'title' => '标签字体',
        'type' => 'file',
        'content' => [],
        'value' => '/assets/fonts/SourceHanSansK-Regular.ttf',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'labelalignment',
        'title' => '标签对齐方式',
        'type' => 'radio',
        'content' => [
            'left' => '左',
            'center' => '居中',
            'right' => '右',
        ],
        'value' => 'center',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'labelfontcolor',
        'title' => '标签字体颜色',
        'type' => 'string',
        'content' => [],
        'value' => '#000000',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'labelmargin',
        'title' => '标签边距',
        'type' => 'string',
        'content' => [],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'logo',
        'title' => '默认显示Logo',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'logopath',
        'title' => 'Logo图片',
        'type' => 'image',
        'content' => [],
        'value' => '/assets/img/qrcode.png',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'logosize',
        'title' => 'Logo大小',
        'type' => 'number',
        'content' => [],
        'value' => '50',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'writefile',
        'title' => '写入文件',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '是否将二维码图片写入文件',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'limitreferer',
        'title' => '防盗链配置',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'allowemptyreferer',
        'title' => '允许空referer',
        'visible' => 'limitreferer=1',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'allowrefererlist',
        'title' => '允许的来源列表',
        'visible' => 'limitreferer=1',
        'type' => 'text',
        'content' => [],
        'value' => 'http://ffaaa.localhost/xxxfs/fdsxx/a.html',
        'rule' => '',
        'msg' => '',
        'tip' => '一行一个来源,域名支持泛域名,*表示所有域名',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'limittextregex',
        'title' => '限定生成文本的正则',
        'type' => 'text',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '限定生成文本的正则，一行一个正则，为空时不限制',
        'ok' => '',
        'visible' => '',
        'extend' => '',
    ],
    [
        'name' => 'limitlabelregex',
        'title' => '限定生成标签的正则',
        'type' => 'text',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '限定生成标签的正则，一行一个正则，为空时不限制',
        'ok' => '',
        'visible' => '',
        'extend' => '',
    ],
    [
        'name' => 'rewrite',
        'title' => '伪静态',
        'type' => 'array',
        'content' => [],
        'value' => [
            'index/index' => '/qrcode$',
            'index/build' => '/qrcode/build$',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
